/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MapRouteImport } from './routes/map'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContentAdminRouteImport } from './routes/content-admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopTraceabilityRouteImport } from './routes/shop.traceability'
import { Route as ShopSupportRouteImport } from './routes/shop.support'
import { Route as ShopReviewsRouteImport } from './routes/shop.reviews'
import { Route as ShopPromotionsRouteImport } from './routes/shop.promotions'
import { Route as ShopProfileRouteImport } from './routes/shop.profile'
import { Route as ShopProductsRouteImport } from './routes/shop.products'
import { Route as ShopOrdersRouteImport } from './routes/shop.orders'
import { Route as ShopLoginRouteImport } from './routes/shop.login'
import { Route as ShopInventoryRouteImport } from './routes/shop.inventory'
import { Route as ShopDashboardRouteImport } from './routes/shop.dashboard'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTraceabilityRouteImport } from './routes/admin.traceability'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNutritionRouteImport } from './routes/admin.nutrition'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAiScansRouteImport } from './routes/admin.ai-scans'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentAdminRoute = ContentAdminRouteImport.update({
  id: '/content-admin',
  path: '/content-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopTraceabilityRoute = ShopTraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSupportRoute = ShopSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ShopRoute,
} as any)
const ShopReviewsRoute = ShopReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPromotionsRoute = ShopPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProfileRoute = ShopProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductsRoute = ShopProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLoginRoute = ShopLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopRoute,
} as any)
const ShopInventoryRoute = ShopInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ShopRoute,
} as any)
const ShopDashboardRoute = ShopDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShopRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTraceabilityRoute = AdminTraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNutritionRoute = AdminNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiScansRoute = AdminAiScansRouteImport.update({
  id: '/ai-scans',
  path: '/ai-scans',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/content-admin': typeof ContentAdminRoute
  '/download': typeof DownloadRoute
  '/home': typeof HomeRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/map': typeof MapRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/shop': typeof ShopRouteWithChildren
  '/trace': typeof TraceRoute
  '/updates': typeof UpdatesRoute
  '/admin/ai-scans': typeof AdminAiScansRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nutrition': typeof AdminNutritionRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/traceability': typeof AdminTraceabilityRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/login': typeof AppLoginRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/shop/dashboard': typeof ShopDashboardRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/login': typeof ShopLoginRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/products': typeof ShopProductsRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/promotions': typeof ShopPromotionsRoute
  '/shop/reviews': typeof ShopReviewsRoute
  '/shop/support': typeof ShopSupportRoute
  '/shop/traceability': typeof ShopTraceabilityRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/content-admin': typeof ContentAdminRoute
  '/download': typeof DownloadRoute
  '/home': typeof HomeRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/map': typeof MapRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/trace': typeof TraceRoute
  '/updates': typeof UpdatesRoute
  '/admin/ai-scans': typeof AdminAiScansRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nutrition': typeof AdminNutritionRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/traceability': typeof AdminTraceabilityRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/login': typeof AppLoginRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/shop/dashboard': typeof ShopDashboardRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/login': typeof ShopLoginRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/products': typeof ShopProductsRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/promotions': typeof ShopPromotionsRoute
  '/shop/reviews': typeof ShopReviewsRoute
  '/shop/support': typeof ShopSupportRoute
  '/shop/traceability': typeof ShopTraceabilityRoute
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/content-admin': typeof ContentAdminRoute
  '/download': typeof DownloadRoute
  '/home': typeof HomeRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/map': typeof MapRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/shop': typeof ShopRouteWithChildren
  '/trace': typeof TraceRoute
  '/updates': typeof UpdatesRoute
  '/admin/ai-scans': typeof AdminAiScansRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nutrition': typeof AdminNutritionRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/traceability': typeof AdminTraceabilityRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/login': typeof AppLoginRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/shop/dashboard': typeof ShopDashboardRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/login': typeof ShopLoginRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/products': typeof ShopProductsRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/promotions': typeof ShopPromotionsRoute
  '/shop/reviews': typeof ShopReviewsRoute
  '/shop/support': typeof ShopSupportRoute
  '/shop/traceability': typeof ShopTraceabilityRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/compare'
    | '/contact'
    | '/content-admin'
    | '/download'
    | '/home'
    | '/knowledge'
    | '/map'
    | '/nutrition'
    | '/profile'
    | '/result'
    | '/scan'
    | '/shop'
    | '/trace'
    | '/updates'
    | '/admin/ai-scans'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/nutrition'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/traceability'
    | '/admin/users'
    | '/app/login'
    | '/knowledge/$slug'
    | '/shop/dashboard'
    | '/shop/inventory'
    | '/shop/login'
    | '/shop/orders'
    | '/shop/products'
    | '/shop/profile'
    | '/shop/promotions'
    | '/shop/reviews'
    | '/shop/support'
    | '/shop/traceability'
    | '/admin/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/compare'
    | '/contact'
    | '/content-admin'
    | '/download'
    | '/home'
    | '/knowledge'
    | '/map'
    | '/nutrition'
    | '/profile'
    | '/result'
    | '/scan'
    | '/trace'
    | '/updates'
    | '/admin/ai-scans'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/nutrition'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/traceability'
    | '/admin/users'
    | '/app/login'
    | '/knowledge/$slug'
    | '/shop/dashboard'
    | '/shop/inventory'
    | '/shop/login'
    | '/shop/orders'
    | '/shop/products'
    | '/shop/profile'
    | '/shop/promotions'
    | '/shop/reviews'
    | '/shop/support'
    | '/shop/traceability'
    | '/admin'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/compare'
    | '/contact'
    | '/content-admin'
    | '/download'
    | '/home'
    | '/knowledge'
    | '/map'
    | '/nutrition'
    | '/profile'
    | '/result'
    | '/scan'
    | '/shop'
    | '/trace'
    | '/updates'
    | '/admin/ai-scans'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/nutrition'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/traceability'
    | '/admin/users'
    | '/app/login'
    | '/knowledge/$slug'
    | '/shop/dashboard'
    | '/shop/inventory'
    | '/shop/login'
    | '/shop/orders'
    | '/shop/products'
    | '/shop/profile'
    | '/shop/promotions'
    | '/shop/reviews'
    | '/shop/support'
    | '/shop/traceability'
    | '/admin/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ContentAdminRoute: typeof ContentAdminRoute
  DownloadRoute: typeof DownloadRoute
  HomeRoute: typeof HomeRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  MapRoute: typeof MapRoute
  NutritionRoute: typeof NutritionRoute
  ProfileRoute: typeof ProfileRoute
  ResultRoute: typeof ResultRoute
  ScanRoute: typeof ScanRoute
  ShopRoute: typeof ShopRouteWithChildren
  TraceRoute: typeof TraceRoute
  UpdatesRoute: typeof UpdatesRoute
  AppLoginRoute: typeof AppLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-admin': {
      id: '/content-admin'
      path: '/content-admin'
      fullPath: '/content-admin'
      preLoaderRoute: typeof ContentAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/traceability': {
      id: '/shop/traceability'
      path: '/traceability'
      fullPath: '/shop/traceability'
      preLoaderRoute: typeof ShopTraceabilityRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/support': {
      id: '/shop/support'
      path: '/support'
      fullPath: '/shop/support'
      preLoaderRoute: typeof ShopSupportRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/reviews': {
      id: '/shop/reviews'
      path: '/reviews'
      fullPath: '/shop/reviews'
      preLoaderRoute: typeof ShopReviewsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/promotions': {
      id: '/shop/promotions'
      path: '/promotions'
      fullPath: '/shop/promotions'
      preLoaderRoute: typeof ShopPromotionsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/profile': {
      id: '/shop/profile'
      path: '/profile'
      fullPath: '/shop/profile'
      preLoaderRoute: typeof ShopProfileRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/products': {
      id: '/shop/products'
      path: '/products'
      fullPath: '/shop/products'
      preLoaderRoute: typeof ShopProductsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/orders': {
      id: '/shop/orders'
      path: '/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/login': {
      id: '/shop/login'
      path: '/login'
      fullPath: '/shop/login'
      preLoaderRoute: typeof ShopLoginRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/inventory': {
      id: '/shop/inventory'
      path: '/inventory'
      fullPath: '/shop/inventory'
      preLoaderRoute: typeof ShopInventoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/dashboard': {
      id: '/shop/dashboard'
      path: '/dashboard'
      fullPath: '/shop/dashboard'
      preLoaderRoute: typeof ShopDashboardRouteImport
      parentRoute: typeof ShopRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traceability': {
      id: '/admin/traceability'
      path: '/traceability'
      fullPath: '/admin/traceability'
      preLoaderRoute: typeof AdminTraceabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nutrition': {
      id: '/admin/nutrition'
      path: '/nutrition'
      fullPath: '/admin/nutrition'
      preLoaderRoute: typeof AdminNutritionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-scans': {
      id: '/admin/ai-scans'
      path: '/ai-scans'
      fullPath: '/admin/ai-scans'
      preLoaderRoute: typeof AdminAiScansRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiScansRoute: typeof AdminAiScansRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNutritionRoute: typeof AdminNutritionRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopsRoute: typeof AdminShopsRoute
  AdminTraceabilityRoute: typeof AdminTraceabilityRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiScansRoute: AdminAiScansRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNutritionRoute: AdminNutritionRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopsRoute: AdminShopsRoute,
  AdminTraceabilityRoute: AdminTraceabilityRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ShopRouteChildren {
  ShopDashboardRoute: typeof ShopDashboardRoute
  ShopInventoryRoute: typeof ShopInventoryRoute
  ShopLoginRoute: typeof ShopLoginRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopProductsRoute: typeof ShopProductsRoute
  ShopProfileRoute: typeof ShopProfileRoute
  ShopPromotionsRoute: typeof ShopPromotionsRoute
  ShopReviewsRoute: typeof ShopReviewsRoute
  ShopSupportRoute: typeof ShopSupportRoute
  ShopTraceabilityRoute: typeof ShopTraceabilityRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopDashboardRoute: ShopDashboardRoute,
  ShopInventoryRoute: ShopInventoryRoute,
  ShopLoginRoute: ShopLoginRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopProductsRoute: ShopProductsRoute,
  ShopProfileRoute: ShopProfileRoute,
  ShopPromotionsRoute: ShopPromotionsRoute,
  ShopReviewsRoute: ShopReviewsRoute,
  ShopSupportRoute: ShopSupportRoute,
  ShopTraceabilityRoute: ShopTraceabilityRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ContentAdminRoute: ContentAdminRoute,
  DownloadRoute: DownloadRoute,
  HomeRoute: HomeRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  MapRoute: MapRoute,
  NutritionRoute: NutritionRoute,
  ProfileRoute: ProfileRoute,
  ResultRoute: ResultRoute,
  ScanRoute: ScanRoute,
  ShopRoute: ShopRouteWithChildren,
  TraceRoute: TraceRoute,
  UpdatesRoute: UpdatesRoute,
  AppLoginRoute: AppLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
